server:
  port: 9999
spring:
  application:
    name: IBUY-PRODUCT #服务名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///aigou-product
    username: root
    password: 940915
#配置mapperxml文件的位置
mybatis-plus:
  mapper-locations: classpath*:cn/itsource/ibuy/mapper/*Mapper.xml


